sudo: required
dist: xenial
language: python
jobs:
  include:
    - name: Test against Python 3.6
      python: 3.6
      script: pytest

    - name: Test against Python 3.7
      python: 3.7
      script: pytest

    - name: Lint test with black
      python: 3.6
      script: black --check django_filters-stubs/

    - name: Lint test with isort
      python: 3.6
      script: isort --check

    - name: Lint test with flake8
      python: 3.6
      script: flake8

before_install:
  - pip install --upgrade pip
  - pip install pipenv
install:
  - pipenv install --dev