name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - name: Setup Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Black
        run: uv run black --check django_filters-stubs/
      
      - name: isort
        run: uv run isort --check django_filters-stubs

      - name: flake8
        run: uv run flake8

      - name: pytest
        run: uv run pytest -vvv
