name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04 # 22.04 doesn't have Python 3.6
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install Pipenv requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black
        run: black --check django_filters-stubs/
      
      - name: isort
        run: isort --check django_filters-stubs

      - name: flake8
        run: flake8

      - name: pytest
        run: pytest -vvv