name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip
      
      - name: Install requirements (3.8+)
        run: |
          pip install -r requirements.in
    

      - name: Black
        run: black --check django_filters-stubs/
      
      - name: isort
        run: isort --check django_filters-stubs

      - name: flake8
        run: flake8 django_filters-stubs

      - name: pytest
        run: pytest -vvv
