name: Publish to PyPi
on:
  release:
    types:
      - "released"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        with:
          python-version: "3.7"

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
